language: node_js
node_js: 
  - "10"
os:
  - linux
  - osx
dist: xenial
osx_image: xcode10.2
sudo: false

cache:
  directories:
  - node_modules
  - $HOME/.cache/electron

addons:
  apt:
    packages:
    - fakeroot
    - rpm
  homebrew:
    packages:
    - mono
    - nuget

branches:
  only:
  - master
  - /^v\d+\.\d+\.\d+/

before_install:
  - if [ $TRAVIS_OS_NAME == linux ] ; then
      sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF ;
      sudo apt-get install apt-transport-https ca-certificates -y ;
      echo "deb https://download.mono-project.com/repo/ubuntu stable-xenial main" | sudo tee /etc/apt/sources.list.d/mono-official-stable.list ;
      sudo apt-get update -qq ;
      sudo apt-get install mono-devel nuget -y ;
    fi

install:
- npm install
- npm update
- ./client/csharpPackageRestore.sh

script:
- if test -z "$TRAVIS_TAG"; then npm run make; fi
after_success: if test -n "$TRAVIS_TAG"; then npm run publish; fi

notifications:
  email:
    - abhishekmishra3@gmail.com