.PHONY: all genbuild delbuild build run clean install help sln

# set the build type for single-config generators.
CMAKE_BUILD_TYPE=Debug

# see https://gist.github.com/sighingnow/deee806603ec9274fd47
# for details on the following snippet to get the OS
# (removed the flags about arch as it is not needed for now)
OSFLAG :=
ifeq ($(OS),Windows_NT)
	OSFLAG = WIN32
else
	UNAME_S := $(shell uname -s)
	ifeq ($(UNAME_S),Linux)
		OSFLAG = LINUX
	endif
	ifeq ($(UNAME_S),Darwin)
		OSFLAG = OSX
	endif
endif

ifeq ($(OSFLAG),WIN32)
	CMAKE_TOOLCHAIN_FILE=${VCPKG_ROOT}/scripts/buildsystems/vcpkg.cmake
else
	CMAKE_TOOLCHAIN_FILE=${VCPKG_ROOT}/scripts/buildsystems/vcpkg.cmake
endif

CMAKE_PRJ_FLAGS=-DCMAKE_TOOLCHAIN_FILE=$(CMAKE_TOOLCHAIN_FILE) -DCMAKE_BUILD_TYPE=$(CMAKE_BUILD_TYPE) -DCMAKE_INSTALL_PREFIX=./install

CMAKE_BUILD_DIR=./build

all: clean build run

genbuild:
	cmake . -B $(CMAKE_BUILD_DIR) $(CMAKE_PRJ_FLAGS)

delbuild:
	rm -fR $(CMAKE_BUILD_DIR)

build:
ifeq ($(OSFLAG),WIN32)
	cmake --build $(CMAKE_BUILD_DIR) --config Debug
else
	cmake --build $(CMAKE_BUILD_DIR)
endif

buildrelease:
ifeq ($(OSFLAG),WIN32)
	cmake --build $(CMAKE_BUILD_DIR) --config Release
else
	echo "buildrelease make target is only supported on multi-config project types."
endif

run:
ifeq ($(OSFLAG),WIN32)
	$(CMAKE_BUILD_DIR)/bin/Debug/picoturtle 
else ifeq ($(OSFLAG),OSX)
	#open -n $(CMAKE_BUILD_DIR)/bin/picoturtle.app --args 
	$(CMAKE_BUILD_DIR)/bin/picoturtle.app/Contents/MacOS/picoturtle --args 
else
	$(CMAKE_BUILD_DIR)/bin/picoturtle 
endif

runrelease:
ifeq ($(OSFLAG),WIN32)
	$(CMAKE_BUILD_DIR)/bin/Release/picoturtle
else
	echo "runrelease make target is only supported on multi-config project types."
endif

clean:
	cmake --build $(CMAKE_BUILD_DIR) --target clean

install:
ifeq ($(OSFLAG),WIN32)
	cmake --build $(CMAKE_BUILD_DIR) --config Release --target install
else
	cmake --build $(CMAKE_BUILD_DIR) --target install
endif

package:	install
ifeq ($(OSFLAG),WIN32)
	cmake --build $(CMAKE_BUILD_DIR) --config Release --target package
else
	cmake --build $(CMAKE_BUILD_DIR) --target package
endif

sln:
ifeq ($(OSFLAG),WIN32)
	cygstart ".\build\picoturtle.sln"
else
	echo "No solution file available on this platform"
endif

help:
		@echo "********************************************************"
		@echo "  Makefile to build [picoturtle]"
		@echo "  (generated by gen-makefile.lua script)"
		@echo "********************************************************"
		@echo "  (The project uses CMake. This Makefile provides"
		@echo "   convenient shortcuts to common build tasks.)"
		@echo ""
		@echo "  all:      Runs the clean, build, and run targets."
		@echo "  build:    Runs the cmake project build target."
		@echo "  run:      Runs the debug executable."
		@echo "  clean:    Runs the cmake project clean target."
		@echo "  install:  Runs the cmake project install target."
		@echo "  delbuild: Deletes the cmake build directory!"
		@echo "  genbuild: Generates the cmake build."
		@echo "********************************************************"
