.PHONY: all genbuild delbuild build test run clean install help sln

# set the build type for single-config generators.
CMAKE_BUILD_TYPE=Debug

# see https://stackoverflow.com/questions/68379786/building-postgres-from-source-throws-utils-errcodes-h-file-not-found-when-ca
MAKELEVEL=0

# see https://gist.github.com/sighingnow/deee806603ec9274fd47
# for details on the following snippet to get the OS
# (removed the flags about arch as it is not needed for now)
OSFLAG :=
ifeq ($(OS),Windows_NT)
	OSFLAG = WIN32
else
	UNAME_S := $(shell uname -s)
	ifeq ($(UNAME_S),Linux)
		OSFLAG = LINUX
	endif
	ifeq ($(UNAME_S),Darwin)
		OSFLAG = OSX
	endif
endif

ifeq ($(OSFLAG),WIN32)
	CMAKE_TOOLCHAIN_FILE="${VCPKG_ROOT}/scripts/buildsystems/vcpkg.cmake"
else
	CMAKE_TOOLCHAIN_FILE=${VCPKG_ROOT}/scripts/buildsystems/vcpkg.cmake
endif

CMAKE_PRJ_FLAGS=-DCMAKE_TOOLCHAIN_FILE=$(CMAKE_TOOLCHAIN_FILE) -DCMAKE_BUILD_TYPE=$(CMAKE_BUILD_TYPE) -DCMAKE_INSTALL_PREFIX=$(CURDIR)/install -DVCPKG_OVERLAY_TRIPLETS=$(CURDIR)/custom-triplets

CMAKE_BUILD_DIR=./build
PROGRAM?=lua/samples/polygons.lua

ifeq ($(OSFLAG),OSX)
	export LUA_CPATH := ${LUA_CPATH};$(realpath ${CMAKE_BUILD_DIR})/lib?.dylib
endif

all: clean build run

genbuild:
	cmake . -B $(CMAKE_BUILD_DIR) $(CMAKE_PRJ_FLAGS)

delbuild:
ifeq ($(OSFLAG),WIN32)
	pwsh -C "rm -fo -R $(CMAKE_BUILD_DIR)"
else
	rm -fR $(CMAKE_BUILD_DIR)
endif

build:
ifeq ($(OSFLAG),WIN32)
	cmake --build $(CMAKE_BUILD_DIR) --config Debug
else
	cmake --build $(CMAKE_BUILD_DIR)
endif

test:
	ctest --test-dir $(CMAKE_BUILD_DIR) --output-on-failure

buildrelease:
ifeq ($(OSFLAG),WIN32)
	cmake --build $(CMAKE_BUILD_DIR) --config Release
else
	echo "buildrelease make target is only supported on multi-config project types."
endif

run:
ifeq ($(OSFLAG),WIN32)
	$(CMAKE_BUILD_DIR)/Debug/picoturtle $(PROGRAM)
else ifeq ($(OSFLAG),OSX)
	$(CMAKE_BUILD_DIR)/picoturtle $(PROGRAM)
else
	$(CMAKE_BUILD_DIR)/bin/picoturtle $(PROGRAM)
endif

runrelease:
ifeq ($(OSFLAG),WIN32)
	$(CMAKE_BUILD_DIR)/bin/Release/picoturtle
else
	echo "runrelease make target is only supported on multi-config project types."
endif

clean:
	cmake --build $(CMAKE_BUILD_DIR) --target clean

install:
ifeq ($(OSFLAG),WIN32)
	cmake --build $(CMAKE_BUILD_DIR) --config Release --target install
else
	cmake --build $(CMAKE_BUILD_DIR) --target install
endif

package:	install
ifeq ($(OSFLAG),WIN32)
	cmake --build $(CMAKE_BUILD_DIR) --config Release --target package
else
	cmake --build $(CMAKE_BUILD_DIR) --target package
endif

sln:
ifeq ($(OSFLAG),WIN32)
	cygstart ".\build\picoturtle.sln"
else
	echo "No solution file available on this platform"
endif

help:
		@echo "********************************************************"
		@echo "  Makefile to build [picoturtle]"
		@echo "  (generated by gen-makefile.lua script)"
		@echo "********************************************************"
		@echo "  (The project uses CMake. This Makefile provides"
		@echo "   convenient shortcuts to common build tasks.)"
		@echo ""
		@echo "  all:      Runs the clean, build, and run targets."
		@echo "  build:    Runs the cmake project build target."
		@echo "  test:     Runs the complete automated test suite."
		@echo "  run:      Runs the debug executable."
		@echo "            Override the Lua file with PROGRAM=path/to/file.lua."
		@echo "  clean:    Runs the cmake project clean target."
		@echo "  install:  Runs the cmake project install target."
		@echo "  delbuild: Deletes the cmake build directory!"
		@echo "  genbuild: Generates the cmake build."
		@echo "********************************************************"
