site_name: "PicoTurtle"

nav:
    - Home: 'index.md'
    - 'Getting Started': 'getting-started.md'
    - 'Turtle Graphics': 'turtle.md'
    - 'User Guide': 'api.md'
    - 'API': 'api.md'
    - 'License': 'LICENSE.md'
    - 'Release Notes': 'CHANGELOG.md'

theme:
  name: material
  palette: 
    scheme: slate
    primary: black
    accent: lime
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
#    - toc.integrate
  