site_name: "PicoTurtle"

nav:
    - Home: 'index.md'
    - 'Getting Started': 'getting-started.md'
    - 'Turtle Graphics': 'turtle.md'
    - 'User Guide': 'userguide.md'
    - 'API': 'api.md'
    - 'Samples':
      - 'sample_empty.md'
      - 'sample_fern.md'
      - 'sample_polygons.md'
      - 'sample_sierpinski.md'
      - 'sample_spiral.md'
      - 'sample_text-demo.md'
      - 'sample_tree.md'
      - 'sample_turtle_basic.md'
    - 'License': 'LICENSE.md'
    - 'Release Notes': 'CHANGELOG.md'

theme:
  name: material
  palette: 
    scheme: slate
    primary: black
    accent: lime

  logo: images/pico.png
  favicon: images/pico.png
    
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - navigation.top
    
    - toc.integrate

    - search.suggest
    - search.highlight

    - header.autohide

extra:
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/abhishekmishra/picoturtle

plugins:
  - search

copyright: Copyright &copy; 2017 - 2023 Abhishek Mishra
