site_name: "PicoTurtle"

repo_url: https://github.com/abhishekmishra/picoturtle
repo_name: abhishekmishra/picoturtle

nav:
    - Home: 'index.md'
    - 'Getting Started': 'getting-started.md'
    - 'Turtle Graphics': 'turtle.md'
    - 'User Guide': 'userguide.md'
    - 'API': 'api.md'
    - 'Samples':
      - samples/index.md
      - 'Basic Program': samples/sample_turtle_basic.md
      - 'Fern': samples/sample_fern.md
      - 'Polygons': samples/sample_polygons.md
      - 'Sierpinski Triangle': samples/sample_sierpinski.md
      - 'Spiral': samples/sample_spiral.md
      - 'Text': samples/sample_text-demo.md
      - 'Tree': samples/sample_tree.md
    - 'License': 'LICENSE.md'
    - 'Release Notes': 'CHANGELOG.md'

theme:
  name: material
  palette:
    scheme: slate
    primary: black
    accent: lime

  logo: images/pico.png
  favicon: images/pico.png
  icon:
    repo: fontawesome/brands/github-alt

  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - navigation.top

    - toc.integrate

    - search.suggest
    - search.highlight

    - header.autohide

    # copy button for code 
    - content.code.copy

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/abhishekmishra/picoturtle
  analytics:
    provider: google
    property: G-X02ZCZMC1F

# for code blocks
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

  # For emojis and icons
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true

copyright: Copyright &copy; 2017 - 2024 Abhishek Mishra
