site_name: "PicoTurtle"

nav:
    - Home: 'index.md'
    - 'Getting Started': 'getting-started.md'
    - 'Turtle Graphics': 'turtle.md'
    - 'Turtle API': 'api.md'
    - 'License': 'LICENSE.md'
    - 'Release Notes': 'CHANGELOG.md'

theme:
  name: material